CREATE TABLE categories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  parent_id BIGINT UNSIGNED NULL,
  name VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL,
  icon_url VARCHAR(512) NULL,
  image_url VARCHAR(512) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_categories_code (code),
  KEY idx_categories_parent_id (parent_id),
  KEY idx_categories_status_sort (status, sort_order),
  KEY idx_categories_deleted_at (deleted_at),
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_no VARCHAR(32) NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  subtitle VARCHAR(255) NULL,
  main_image_url VARCHAR(512) NULL,
  description LONGTEXT NULL,
  unit VARCHAR(32) NOT NULL,
  origin VARCHAR(128) NULL,
  storage_method VARCHAR(128) NULL,
  shelf_status VARCHAR(16) NOT NULL DEFAULT 'draft',
  recommend_status TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_products_product_no (product_no),
  KEY idx_products_category_status (category_id, shelf_status),
  KEY idx_products_recommend_sort (recommend_status, sort_order),
  KEY idx_products_deleted_at (deleted_at),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE product_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  image_url VARCHAR(512) NOT NULL,
  image_type VARCHAR(16) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_product_images_product_type_sort (product_id, image_type, sort_order),
  CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skus (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sku_no VARCHAR(32) NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  spec_json JSON NULL,
  cost_price DECIMAL(12,2) NULL,
  sale_price DECIMAL(12,2) NOT NULL,
  market_price DECIMAL(12,2) NULL,
  member_price DECIMAL(12,2) NULL,
  weight DECIMAL(12,3) NULL,
  weight_unit VARCHAR(16) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'enabled',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_skus_sku_no (sku_no),
  KEY idx_skus_product_status (product_id, status),
  KEY idx_skus_deleted_at (deleted_at),
  CONSTRAINT fk_skus_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT chk_skus_sale_price_non_negative CHECK (sale_price >= 0),
  CONSTRAINT chk_skus_cost_price_non_negative CHECK (cost_price IS NULL OR cost_price >= 0),
  CONSTRAINT chk_skus_market_price_non_negative CHECK (market_price IS NULL OR market_price >= 0),
  CONSTRAINT chk_skus_member_price_non_negative CHECK (member_price IS NULL OR member_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
