CREATE TABLE refunds (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  refund_no VARCHAR(40) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  order_no VARCHAR(32) NOT NULL,
  payment_id BIGINT UNSIGNED NOT NULL,
  payment_no VARCHAR(40) NOT NULL,
  user_id CHAR(36) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  provider_refund_id VARCHAR(128) NULL,
  provider_event_id VARCHAR(128) NULL,
  amount BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  reason VARCHAR(255) NULL,
  source VARCHAR(32) NOT NULL,
  requested_by VARCHAR(64) NOT NULL,
  requested_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  success_at DATETIME(3) NULL,
  failed_at DATETIME(3) NULL,
  closed_at DATETIME(3) NULL,
  provider_response JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_refunds_refund_no (refund_no),
  UNIQUE KEY uk_refunds_order_id (order_id),
  KEY idx_refunds_order_no (order_no),
  KEY idx_refunds_payment_id (payment_id),
  KEY idx_refunds_payment_no (payment_no),
  KEY idx_refunds_user_id (user_id),
  KEY idx_refunds_status_created_at (status, created_at),
  KEY idx_refunds_provider_refund_id (provider_refund_id),
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
  CONSTRAINT fk_refunds_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_refunds_amount_positive CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE refund_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  refund_id BIGINT UNSIGNED NULL,
  refund_no VARCHAR(40) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  old_status VARCHAR(32) NULL,
  new_status VARCHAR(32) NULL,
  provider VARCHAR(32) NULL,
  provider_event_id VARCHAR(128) NULL,
  provider_refund_id VARCHAR(128) NULL,
  payload_hash CHAR(64) NOT NULL,
  payload JSON NULL,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  process_result VARCHAR(64) NULL,
  error_message VARCHAR(255) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_refund_events_refund_id (refund_id),
  KEY idx_refund_events_refund_no (refund_no),
  KEY idx_refund_events_provider_refund_id (provider_refund_id),
  KEY idx_refund_events_created_at (created_at),
  UNIQUE KEY uk_refund_events_provider_event (provider, provider_event_id),
  CONSTRAINT fk_refund_events_refund FOREIGN KEY (refund_id) REFERENCES refunds(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
