CREATE TABLE payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_no VARCHAR(40) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  order_no VARCHAR(32) NOT NULL,
  user_id CHAR(36) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  channel VARCHAR(32) NOT NULL DEFAULT 'MINIAPP',
  status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
  amount BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  provider_trade_no VARCHAR(96) NULL,
  provider_prepay_id VARCHAR(128) NULL,
  client_request_id VARCHAR(96) NULL,
  expire_at DATETIME(3) NOT NULL,
  paid_at DATETIME(3) NULL,
  closed_at DATETIME(3) NULL,
  failed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_payments_payment_no (payment_no),
  UNIQUE KEY uk_payments_client_request (user_id, order_id, provider, client_request_id),
  KEY idx_payments_order_id (order_id),
  KEY idx_payments_order_no (order_no),
  KEY idx_payments_user_id (user_id),
  KEY idx_payments_status_created_at (status, created_at),
  KEY idx_payments_provider_trade_no (provider_trade_no),
  KEY idx_payments_provider_status (provider, status),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT chk_payments_amount_positive CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE payment_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_id BIGINT UNSIGNED NULL,
  payment_no VARCHAR(40) NOT NULL,
  provider VARCHAR(32) NOT NULL,
  event_type VARCHAR(48) NOT NULL,
  provider_event_id VARCHAR(128) NULL,
  provider_trade_no VARCHAR(96) NULL,
  payload_hash CHAR(64) NOT NULL,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  process_result VARCHAR(64) NULL,
  error_message VARCHAR(255) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  KEY idx_payment_events_payment_id (payment_id),
  KEY idx_payment_events_payment_no (payment_no),
  KEY idx_payment_events_provider_trade_no (provider_trade_no),
  KEY idx_payment_events_created_at (created_at),
  UNIQUE KEY uk_payment_events_provider_event (provider, provider_event_id),
  CONSTRAINT fk_payment_events_payment FOREIGN KEY (payment_id) REFERENCES payments(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
